apiVersion:  v1
kind:  PersistantVolume
metadata:
  name:  mongo-pv 
spec:
  capacity:
    storage:  3Gi
  accessModes:
    - ReadWriteMany
  PersistantVolumeReclaimPolicy:  Retain
  nfs:
    path: /var/nfs/general
    server: 13.127.183.82
        
